### PR TITLE
Update pagecontroller.php

### PR DESCRIPTION
**Pull request by sm4rty89**
Added the possibility for downloading and converting playlists.

Its only working for complete playlists. if there is one video not available the script will give an error back.
couldnt get it fixed. I used the -i option of youtube-dl for ignore-errors but its not working for me.

### CODE REVIEW

**Comment by shibby** [comment]
thanks for your contrbition. it seems clear. i cannot test your changes right now. did you checked for a single file?

**Comment by sm4rty89** [comment]
for me there is no problem. its working with playlists and single files.
but for the playlist all videos have to exist. Is there one video 
missing because its deleted or the account suspended the script cant 
download the playlist because youtubedl gives an error.



Am 03.05.2015 um 19:30 schrieb Guven:

**Comment by shibby** [comment]
it's youtubedl's problem, not our. we can give a information. thanks for your contribition.

**Comment by sm4rty89** [comment]
No its not youtube-dl's problem its the problem of the pagecontroller.php.

when it downloads the video youtube-dl returns the error and writes it 
in the $process.  your if statement reads the error and exits the script.
try to remove the else statement then it downloads all videos except the 
missing ones.



Am 04.05.2015 um 10:32 schrieb Guven:

**Comment by shibby** [comment]
hah, ok. thanks for information. i ll try asap.

**Pull request merged**
